<div align="right" vertical-align="middle" style="border: 2px solid;border-radius: 5px;background-color:lightgrey;padding:5px;padding-right:20px;padding-left:10px;">
        <a style="color:black;text-decoration:none;" title="Home" href="../index.ipynb">
            <img src="../../css/iconmonstr-christmas-house-icon.svg" height = "30" width = "30" style="display:inline">
        </a>
        &nbsp;
        <b>|</b>
        &nbsp;
        <a style="color:black;text-decoration:none;" title="Build" href="../build_docs/build.ipynb">
            <img src="../../css/iconmonstr-puzzle-icon.svg" height = "30" width = "30" style="display:inline">
        </a>
        <a style="color:black;text-decoration:none;" title="Assemble" href="../assemble_docs/assemble.ipynb">
            <img src="../../css/iconmonstr-puzzle-17-icon.svg" height = "30" width = "30" style="display:inline">
        </a>
        <a style="color:black;text-decoration:none;" title="Query" href="query.ipynb">
            <img src="../../css/iconmonstr-flask-3-icon.svg" height = "30" width = "30" style="display:inline">
        </a>
</div>

# Basic Mining

## EGRIN2.0 MongoDB query using `agglom`

### In a nutshell

### Set-up

*Make sure ./egrin-tools/ folder is in your python path*

You can do this on Mac/Linux by adding the path to you Bash Shell Startup Files, e.g. ~/.bashrc or ~/.bash_profile

for example in ~/.bash_profile add the following line:

`export PYTHONPATH=$PYTHONPATH:path/to/egrin2-tools/`

### Load required modules

In [4]:
from query.egrin2_query import *

host = "baligadev"
db = "eco_db"
port = 27017

There are several dependencies that need to be satisfied, including:
- pymongo
- numpy
- pandas
- joblib
- scipy
- statsmodels
- itertools

### `agglom` function

#### Example 1: find co-regulated genes

In this example, we will mine the ensemble for genes discovered in biclusters with the gene *E. coli* carbamoyl phosphate synthetase, carA (b0032)

In [5]:
carA_genes = agglom( x = "b0032", x_type = "genes", y_type = "genes", host=host, db=db, port=port )

Using "or" logic
Reverting to translation by single matches. Defining 'input_type' will dramatically speed up query.

In [6]:
carA_genes

       counts  all_counts           pval        qval_BH  qval_bonferroni
b1062     152         198   0.000000e+00   0.000000e+00     0.000000e+00
b0336     153         198   0.000000e+00   0.000000e+00     0.000000e+00
b0337     154         198   0.000000e+00   0.000000e+00     0.000000e+00
b4244     167         198   0.000000e+00   0.000000e+00     0.000000e+00
b4245     169         198   0.000000e+00   0.000000e+00     0.000000e+00
b0033     173         198   0.000000e+00   0.000000e+00     0.000000e+00
b0032     198         198   0.000000e+00   0.000000e+00     0.000000e+00
b2476     142         198  3.783051e-300  4.073085e-298    3.665776e-297
b2499     142         198  3.783051e-300  4.073085e-298    3.665776e-297
b2313     141         198  5.664712e-297  4.574255e-295    5.489106e-294
b2557     141         198  5.664712e-297  4.574255e-295    5.489106e-294
b2312     141         198  5.664712e-297  4.574255e-295    5.489106e-294
b0522     138         198  1.477589e-287  1.101372e-285    1.431783e-284
b1849     136         198  2.280977e-281  1.578762e-279    2.210267e-278
b4006     132         198  3.382871e-269  2.185335e-267    3.278002e-266
b0523     129         198  3.043903e-260  1.843464e-258    2.949542e-257
b3654     128         198  2.728256e-257  1.555106e-255    2.643680e-254
b4246     126         198  1.964952e-251  1.057799e-249    1.904038e-248
b2500     122         198  6.646122e-240  3.389522e-238    6.440093e-237
b2497     112         198  4.061863e-212  1.967973e-210    3.935945e-209
b4064     102         198  9.823972e-186  4.533061e-184    9.519429e-183
b0945      96         198  1.511792e-170  6.658758e-169    1.464927e-167
b4005      89         198  2.020583e-153  8.512805e-152    1.957945e-150
b3941      58         198   3.940658e-85   1.591041e-83     3.818498e-82
b3359      57         198   3.886443e-83   1.448447e-81     3.765963e-80
b3829      57         198   3.886443e-83   1.448447e-81     3.765963e-80
b4024      56         198   3.714681e-81   1.333158e-79     3.599526e-78
b0908      55         198   3.440262e-79   1.149522e-77     3.333614e-76
b3774      55         198   3.440262e-79   1.149522e-77     3.333614e-76
b3008      54         198   3.086539e-77   9.647922e-76     2.990856e-74
...       ...         ...            ...            ...              ...
b2599       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b3715       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b1247       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b0854       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b3574       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b0537       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b0010       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b3544       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b3115       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b2495       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b0889       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b0157       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b0078       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b3541       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b0074       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b4471       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b3113       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b0070       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b3114       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b0293       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b2177       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b1244       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b2182       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b0349       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b2000       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b0377       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b0073       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b1145       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b1603       3         198   3.154301e-02   1.180123e-01     1.000000e+00
b2442       3         198   3.154301e-02   1.180123e-01     1.000000e+00

[259 rows x 5 columns]

There are several things to note in this query.

First the arguments:
- `x` specfies the query. This can be `gene(s)`, `condition(s)`, `GRE(s)`, or `bicluster(s)`. `x` can be a single entity or a list of entitites of the same type. 
- `x_type` indicates the type of `x`. This can include `gene`, `condition`, `gres`, and `biclusters`. Basically: "what is x?" The parameter typing is pretty flexible, so - for example - `rows` can be used instead of `genes`.
- `y_type` is the type of. Again, `genes`, `conditions`, `gres`, or `biclusters`. 
- `host` specifies where the MongoDB database is running. In this case it is running on a machine called `primordial` (my box). If you are hosting the database locally this would be `localhost`
- `db` is the name of the database you want to perform the query in. Typically databases are specified by the three letter organism code (e.g., **eco**) followed by **_db**. A list of maintained databases is available <a href="../check_dbs.ipynb">here</a>.

Also note the output:

This is a table of all genes that are frequently co-discovered in biclusters with b0032 (carA). They are sorted by their relative "enrichment" in the sample `x` (where lower pval = greater enrichment). This is quantified by the hypergeometric distribution. To account for multiple testing, two corrections are  included: Benjamini-Hochber correction (`qval_BH`; less stringent) and Bonferrnoni correction (`qval_bonferroni`; more stringent).

We can easily change the format of `x`, which makes it easy to specify genes in any format. Let's try to include a list of genes with two different naming formats. This time we will only return the first few elements using `.head()`

In [7]:
agglom( x = ["b0032","pyrL","b0031"], x_type="genes", y_type= "genes", host=host, db=db, port=port ).head()

Using "or" logic
Reverting to translation by single matches. Defining 'input_type' will dramatically speed up query.

       counts  all_counts  pval  qval_BH  qval_bonferroni
b4244     179         198     0        0                0
b0033     180         198     0        0                0
b4245     185         198     0        0                0
b4246     198         198     0        0                0
b0031     198         198     0        0                0

The lookup table is pretty extensive for genes (it comes from MicrobesOnline) so anything from common name to GI number can be matched. Cool, huh?

You can also specify the type of logic to use in grouping your query. For example, do you want do find biclusters where all genes `x` in your query are present (`and` logic) or biclusters where at least one of the genes is present (`or` logic). You can change the logical grouping of your query by specifying the `logic` parameter. This parameter can take one of three values: `and`, `or`, or `nor`. By default the command uses `and` logic.

Here we change the logic employed in the previous query to "and", meaning that a bicluster must contain **all** of the query genes. Notice how the values change.

In [8]:
agglom( x = ["b0032","pyrL","b0031"], x_type="genes", y_type= "genes", logic = "and", host=host, db=db, port=port ).head()

Using "and" logic
Reverting to translation by single matches. Defining 'input_type' will dramatically speed up query.

       counts  all_counts          pval       qval_BH  qval_bonferroni
b4246      25         198  0.000000e+00  0.000000e+00     0.000000e+00
b0032      25         198  0.000000e+00  0.000000e+00     0.000000e+00
b0031      25         198  0.000000e+00  0.000000e+00     0.000000e+00
b4006      24         198  5.510260e-57  3.981163e-55     1.592465e-54
b4245      23         198  2.604624e-53  1.075338e-51     7.527363e-51

Logical operations can provide a substantial amount of power to your queries. For example, imagine that you not only want to know when *b0032*, *pyrL*, and *b0031* are co-regulated **but also when they are not**. This can be done using the logical operator `nor`.

First we query for conditions where they are co-regulated:

In [11]:
agglom( x = ["b0032","pyrL","b0031"], x_type="genes", y_type= "conditions", host=host, db=db, logic = "or"  ).head()

Using "or" logic
Reverting to translation by single matches. Defining 'input_type' will dramatically speed up query.

,counts,all_counts,pval,qval_BH,qval_bonferroni
rb_del_rpoS_biofilm,240,12921,2.849586e-13,7.228851e-11,1.327907e-10
biofilm_24hr_del_yceP,239,12879,3.889790e-13,7.228851e-11,1.812642e-10
ik_H2_T4,232,12380,4.653767e-13,7.228851e-11,2.168655e-10
MG1063_uninduced_t180,232,12543,2.190004e-12,2.551355e-10,1.020542e-09
rb_del_rpoS_exponential,226,12198,5.366065e-12,5.001173e-10,2.500586e-09

Now we can compare these conditions to conditions that are exluded from biclusters where at least one of the genes is present:

In [12]:

agglom( x = ["b0032","pyrL","b0031"], x_type="genes", y_type= "conditions", host=host, db=db, logic = "nor"  ).head()

Using "nor" logic
Reverting to translation by single matches. Defining 'input_type' will dramatically speed up query.

,counts,all_counts,pval,qval_BH,qval_bonferroni
har_S0_R_noIPTG,12933,13045,2.442307e-09,0.000001,0.000001
MOPS_K_dps_stationary2,10149,10230,5.916970e-09,0.000001,0.000003
BW25113_K_tnaA_30C_biofilm_indole_control,11308,11403,9.537266e-09,0.000001,0.000004
MG1655_kanamycin_t60,11240,11337,5.362424e-08,0.000006,0.000025
dilution_t3,12110,12219,1.446307e-07,0.000013,0.000067